{% set version = "0.2.2" %}
{% set name = "ubermagutil" %}
{% set sha256 = "779a8c3334c8f4493f01f66724301ecab1c022b246238985cc7898f674216ab1" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: pip install --no-deps . -vvv

requirements:
  build:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy
    - pytest

test:
  imports:
    - ubermagutil
    - ubermagutil.typesystem
    
  commands:
    - python -c "import sys; import ubermagutil as uu; sys.exit(uu.test())"

about:
  home: http://ubermag.github.io/
  license: BSD-3-clause
  license_family: BSD
  license_file: LICENSE
  summary: Python utilities package used across Ubermag.
  doc_url: http://ubermagutil.readthedocs.io
  dev_url: https://github.com/ubermag/ubermagutil

  description: |
    `ubermagutil` is a Python package used across [Ubermag](http://ubermag.github.io). It provides:

      - definition of the type-system and
      - conversion of units.

extra:
  recipe-maintainers:
    - marijanbeg
    - fangohr
