{% set name = "ubermagutil" %}
{% set version = "0.63.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b440da716aecca883caa291f6d561142e0afcdbb00800e0f83e99762ab77ff98

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - numpy >=1.19
    - pytest >=6.2
    - setuptools
    - tqdm

test:
  imports:
    - ubermagutil
    - ubermagutil.typesystem
    - ubermagutil.units
  commands:
    - python -c "import sys; import ubermagutil; sys.exit(ubermagutil.test())"

about:
  home: http://ubermag.github.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Utility package used across Ubermag.
  doc_url: https://ubermag.github.io/documentation/ubermagutil.html
  dev_url: https://github.com/ubermag/ubermagutil

extra:
  recipe-maintainers:
    - marijanbeg
    - lang-m
    - fangohr
    - samjrholt
    - swapneelap
