{% set name = "ubermagutil" %}
{% set version = "0.64.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5441c9eef560b087247151073191c28cfd5a2762d823b1392458e45476073c6e

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.19
    - pytest >=6.2
    - tqdm

test:
  requires:
    - python {{ python_min }}
  imports:
    - ubermagutil
    - ubermagutil.typesystem
    - ubermagutil.units
  commands:
    - python -c "import sys; import ubermagutil; sys.exit(ubermagutil.test())"

about:
  home: http://ubermag.github.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Utility package used across Ubermag.
  doc_url: https://ubermag.github.io/documentation/ubermagutil.html
  dev_url: https://github.com/ubermag/ubermagutil

extra:
  recipe-maintainers:
    - marijanbeg
    - lang-m
    - fangohr
    - samjrholt
    - swapneelap
