{% set name = "ubermagutil" %}
{% set version = "0.2.5" %}
{% set sha256 = "72939563c4a541539b2c94448dbd96606c8e325ef9d0c047e5d6d91c2df4b455" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy
    - pytest

test:
  imports:
    - ubermagutil
    - ubermagutil.typesystem
    - ubermagutil.units
  commands:
    - python -c "import sys; import ubermagutil as uu; sys.exit(uu.test())"

about:
  home: http://ubermag.github.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Python utilities package used across Ubermag.'
  doc_url: http://ubermagutil.readthedocs.io
  dev_url: https://github.com/ubermag/ubermagutil

extra:
  recipe-maintainers:
    - marijanbeg
    - fangohr
