{% set name = "ubermagutil" %}
{% set version = "0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a301fec86885b304873ed617c1e7eb40441e11cf16ae272d20a27a2c6ab80a8f

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - numpy >=1.19
    - pytest >=6.2
    - setuptools

test:
  imports:
    - ubermagutil
    - ubermagutil.typesystem
    - ubermagutil.units
  commands:
    - python -c "import sys; import ubermagutil; sys.exit(ubermagutil.test())"

about:
  home: http://ubermag.github.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Utility package used across Ubermag.
  doc_url: http://ubermagutil.readthedocs.io
  dev_url: https://github.com/ubermag/ubermagutil

extra:
  recipe-maintainers:
    - marijanbeg
    - lang-m
    - fangohr
