{% set version = "0.1.1" %}
{% set name = "ubermagutil" %}
{% set sha256 = "99297c0826fb9737ffd9e09239d1169a62ed6231614e0be5face1874386f3521" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: pip install --no-deps .

requirements:
  build:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy
    - pytest

test:
  imports:
    - ubermagutil
    - ubermagutil.typesystem
    
  commands:
    - python -c "import sys; import ubermagutil as uu; sys.exit(uu.test())"

about:
  home: http://ubermag.github.io/
  license: BSD 3-clause
  license_file: LICENSE
  summary: Utilities for Ubermag
  dev_url: https://github.com/ubermag/ubermagutil

extra:
  recipe-maintainers:
    - marijanbeg
