{% set name = "ubermagutil" %}
{% set version = "0.63.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 91ba997c24304c1cc9a04f078ccecc19304652efe9b022e007fa8828d3e7a5ae

build:
  noarch: python
  number: 2
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.19
    - pytest >=6.2
    - tqdm

test:
  requires:
    - python {{ python_min }}
  imports:
    - ubermagutil
    - ubermagutil.typesystem
    - ubermagutil.units
  commands:
    - python -c "import sys; import ubermagutil; sys.exit(ubermagutil.test())"

about:
  home: http://ubermag.github.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Utility package used across Ubermag.
  doc_url: https://ubermag.github.io/documentation/ubermagutil.html
  dev_url: https://github.com/ubermag/ubermagutil

extra:
  recipe-maintainers:
    - marijanbeg
    - lang-m
    - fangohr
    - samjrholt
    - swapneelap
