{% set version = "0.2.4" %}
{% set name = "ubermagutil" %}
{% set sha256 = "f01b6b071e9b84bd7d11194d0fd9b09c8624c3c4139a43b335027c1b5eb3ef26" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: pip install --no-deps . -vvv

requirements:
  build:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - numpy
    - pytest

test:
  imports:
    - ubermagutil
    - ubermagutil.typesystem
    - ubermagutil.units

  commands:
    - python -c "import sys; import ubermagutil as uu; sys.exit(uu.test())"

about:
  home: http://ubermag.github.io/
  license: BSD-3-clause
  license_family: BSD
  license_file: LICENSE
  summary: Python utilities package used across Ubermag.
  doc_url: http://ubermagutil.readthedocs.io
  dev_url: https://github.com/ubermag/ubermagutil

  description: |
    `ubermagutil` is a Python package used across Ubermag. It provides:
      - definition of the type-system and
      - conversion of units.

extra:
  recipe-maintainers:
    - marijanbeg
    - fangohr
