travis:
  secure:
    BINSTAR_TOKEN: PrOLlPCUzIGPaoxB2b7ZENG3wIwGCs3C8YpnCJeg4kEUcxTSTEkVepLC1BfVDKJ30nhuZTwEMZ8hqSA0iP90306XccJygQ9I0nsdvTLGqg6M4qh4S2M4DwjL9M0mRE5mwSUYzo9+wLDwNFM8daFpKuMe8LFkO8EvwODJ6144is1dfoqTpOYVevc3MkwPbqur8X5f9KNp7x92NheFU38jP3VAcTbVZLfrCKOcJChzP4lma5JDNatu3WHs5LqhTRP53BlnbzndTLTA4ejXOnSWyWJYTjkEOa/A0Th/YR7gIBm/iQPt1ZnLB/kdQQR2St5zuXVoTllz15rdN9m7iYdz7SlQ1jnvLrbR+2HvX0/nXfcifVOWXkX2yZEPsB9Z+OfIkbg+yOu+qSFoLr8Q40cWZ2xLLLPoCvhF6Sh1uyKNqc/iPESt1uVYwib/k5Yut7a66rPdniO16jET7XMbVSvmYBlbuYtKxpFeoQ7X0dCVoYrDqf/QtSPg+93y2KAfv+cBwOEWmUo8kvvOeB4aA7EDtjp3V3pxaGe6Lk5MBSyXv93o3Ytlkf96ZEIGpM4DKNH6OkESuW7eavilTSvWKVQwghhzJkN4I2Kd4+MaaXGSrhObCnar5wQ6tLZ3pfwp+3N/v5A3S/8Z9/QmNmjqA8J7g+YXND0h8yk4At0alPhSQwo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
