travis:
  secure:
    BINSTAR_TOKEN: 3aj67N6Ohjc1ob2YQ/DtQxAfHTsCiirGm66lrw+/jX3GnzATGO+i6/hNMfpDgvGXCWbWi63ISIZ5MmHVNbz72TBgLHSqClTe7Ubc3wR8+8jOkIZ+PRuypXmDQhwd65UhmULa8m2vDuQ6t45MtfW6AxCNqGWvA3f7Mv0KkhMa5KhaPMm5S77V6J9zU2POU9cluCyIXdDawgphn2yuMa7NoNA2ebHDl+hQFEc+Azq6UWSE908uH9Gd1AuQWdrxXpzL/0nrywuA8tLuMenKr653Jy8FUcQaKDzIAI/wSOKm8z303iUuKj7LBcUvZlOsnyLO66xIfQ7oEg7vc91pmF/FpSDmAUAfkdSsqrh6ohlqHi5DT1mlasHNeoefBiLqlOrZmZp16lDgjKl+oLTMI4vLClZyc9trRSmcNxtxZXpAsx0GbSaJ822r1ZB3d4NVugSeRLUVOMqGCzwLllDTc5xcVbcnvRNLyPL5q0LtN8yYqhoePFDqaUDnYLELvskCbGaAzwCkEGMqI5f3xT1J0WPqeDqrKUp2d9DZSvaglRPTKGeb6/wSb61iZVQlpjM0EdL/GrL2LyiVTJTpAF7QfirQYei8AlM5hpNDvRgJ1x6IgsoO8I7ObQwwJNUsZY0189j4/vpU5SfedtOPsRbGuh1wnGaLh/mN6azP/7aVVK3xFvQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
